default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - calico/node:v3.26.1
  - calico/pod2daemon-flexvol:v3.26.1
  - calico/cni:v3.26.1
  - calico/kube-controllers:v3.26.1
